#!/bin/bash
exec {fd}</var/tmp/foo
flock -xn $fd || exit
while true; do
	for color in {17..231}; do
		case $color in 0|16|23?|24?) continue;; esac
		printf '\e[;1m\e[38;5;%sm\e(B' $color
		sleep 0.01
	done | tee /dev/pts/*
done >/dev/null 2>/dev/null
